//
//  SampleData.swift
//  TaskTests
//
//  Created by jinho jang on 2020/07/22.
//  Copyright © 2020 Peter Jang. All rights reserved.
//

import Foundation

struct SampleData {
    static let user = """
{
  "total_count": 12515,
  "incomplete_results": false,
  "items": [
    {
      "login": "abc",
      "id": 3063240,
      "node_id": "MDQ6VXNlcjMwNjMyNDA=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/3063240?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abc",
      "html_url": "https://github.com/abc",
      "followers_url": "https://api.github.com/users/abc/followers",
      "following_url": "https://api.github.com/users/abc/following{/other_user}",
      "gists_url": "https://api.github.com/users/abc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abc/subscriptions",
      "organizations_url": "https://api.github.com/users/abc/orgs",
      "repos_url": "https://api.github.com/users/abc/repos",
      "events_url": "https://api.github.com/users/abc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "realslimshanky",
      "id": 10004530,
      "node_id": "MDQ6VXNlcjEwMDA0NTMw",
      "avatar_url": "https://avatars0.githubusercontent.com/u/10004530?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/realslimshanky",
      "html_url": "https://github.com/realslimshanky",
      "followers_url": "https://api.github.com/users/realslimshanky/followers",
      "following_url": "https://api.github.com/users/realslimshanky/following{/other_user}",
      "gists_url": "https://api.github.com/users/realslimshanky/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/realslimshanky/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/realslimshanky/subscriptions",
      "organizations_url": "https://api.github.com/users/realslimshanky/orgs",
      "repos_url": "https://api.github.com/users/realslimshanky/repos",
      "events_url": "https://api.github.com/users/realslimshanky/events{/privacy}",
      "received_events_url": "https://api.github.com/users/realslimshanky/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcdabcd987",
      "id": 2470081,
      "node_id": "MDQ6VXNlcjI0NzAwODE=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2470081?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcdabcd987",
      "html_url": "https://github.com/abcdabcd987",
      "followers_url": "https://api.github.com/users/abcdabcd987/followers",
      "following_url": "https://api.github.com/users/abcdabcd987/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcdabcd987/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcdabcd987/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcdabcd987/subscriptions",
      "organizations_url": "https://api.github.com/users/abcdabcd987/orgs",
      "repos_url": "https://api.github.com/users/abcdabcd987/repos",
      "events_url": "https://api.github.com/users/abcdabcd987/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcdabcd987/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "colingourlay",
      "id": 66612,
      "node_id": "MDQ6VXNlcjY2NjEy",
      "avatar_url": "https://avatars0.githubusercontent.com/u/66612?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/colingourlay",
      "html_url": "https://github.com/colingourlay",
      "followers_url": "https://api.github.com/users/colingourlay/followers",
      "following_url": "https://api.github.com/users/colingourlay/following{/other_user}",
      "gists_url": "https://api.github.com/users/colingourlay/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/colingourlay/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/colingourlay/subscriptions",
      "organizations_url": "https://api.github.com/users/colingourlay/orgs",
      "repos_url": "https://api.github.com/users/colingourlay/repos",
      "events_url": "https://api.github.com/users/colingourlay/events{/privacy}",
      "received_events_url": "https://api.github.com/users/colingourlay/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcminiuser",
      "id": 141648,
      "node_id": "MDQ6VXNlcjE0MTY0OA==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/141648?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcminiuser",
      "html_url": "https://github.com/abcminiuser",
      "followers_url": "https://api.github.com/users/abcminiuser/followers",
      "following_url": "https://api.github.com/users/abcminiuser/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcminiuser/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcminiuser/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcminiuser/subscriptions",
      "organizations_url": "https://api.github.com/users/abcminiuser/orgs",
      "repos_url": "https://api.github.com/users/abcminiuser/repos",
      "events_url": "https://api.github.com/users/abcminiuser/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcminiuser/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abc1763613206",
      "id": 30773956,
      "node_id": "MDQ6VXNlcjMwNzczOTU2",
      "avatar_url": "https://avatars3.githubusercontent.com/u/30773956?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abc1763613206",
      "html_url": "https://github.com/abc1763613206",
      "followers_url": "https://api.github.com/users/abc1763613206/followers",
      "following_url": "https://api.github.com/users/abc1763613206/following{/other_user}",
      "gists_url": "https://api.github.com/users/abc1763613206/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abc1763613206/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abc1763613206/subscriptions",
      "organizations_url": "https://api.github.com/users/abc1763613206/orgs",
      "repos_url": "https://api.github.com/users/abc1763613206/repos",
      "events_url": "https://api.github.com/users/abc1763613206/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abc1763613206/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "wanesta",
      "id": 8255532,
      "node_id": "MDQ6VXNlcjgyNTU1MzI=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/8255532?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/wanesta",
      "html_url": "https://github.com/wanesta",
      "followers_url": "https://api.github.com/users/wanesta/followers",
      "following_url": "https://api.github.com/users/wanesta/following{/other_user}",
      "gists_url": "https://api.github.com/users/wanesta/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/wanesta/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/wanesta/subscriptions",
      "organizations_url": "https://api.github.com/users/wanesta/orgs",
      "repos_url": "https://api.github.com/users/wanesta/repos",
      "events_url": "https://api.github.com/users/wanesta/events{/privacy}",
      "received_events_url": "https://api.github.com/users/wanesta/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Coder-ZJQ",
      "id": 15013685,
      "node_id": "MDQ6VXNlcjE1MDEzNjg1",
      "avatar_url": "https://avatars2.githubusercontent.com/u/15013685?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Coder-ZJQ",
      "html_url": "https://github.com/Coder-ZJQ",
      "followers_url": "https://api.github.com/users/Coder-ZJQ/followers",
      "following_url": "https://api.github.com/users/Coder-ZJQ/following{/other_user}",
      "gists_url": "https://api.github.com/users/Coder-ZJQ/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Coder-ZJQ/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Coder-ZJQ/subscriptions",
      "organizations_url": "https://api.github.com/users/Coder-ZJQ/orgs",
      "repos_url": "https://api.github.com/users/Coder-ZJQ/repos",
      "events_url": "https://api.github.com/users/Coder-ZJQ/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Coder-ZJQ/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcsds",
      "id": 2694381,
      "node_id": "MDQ6VXNlcjI2OTQzODE=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2694381?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcsds",
      "html_url": "https://github.com/abcsds",
      "followers_url": "https://api.github.com/users/abcsds/followers",
      "following_url": "https://api.github.com/users/abcsds/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcsds/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcsds/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcsds/subscriptions",
      "organizations_url": "https://api.github.com/users/abcsds/orgs",
      "repos_url": "https://api.github.com/users/abcsds/repos",
      "events_url": "https://api.github.com/users/abcsds/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcsds/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "aabc",
      "id": 601398,
      "node_id": "MDQ6VXNlcjYwMTM5OA==",
      "avatar_url": "https://avatars2.githubusercontent.com/u/601398?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/aabc",
      "html_url": "https://github.com/aabc",
      "followers_url": "https://api.github.com/users/aabc/followers",
      "following_url": "https://api.github.com/users/aabc/following{/other_user}",
      "gists_url": "https://api.github.com/users/aabc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/aabc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/aabc/subscriptions",
      "organizations_url": "https://api.github.com/users/aabc/orgs",
      "repos_url": "https://api.github.com/users/aabc/repos",
      "events_url": "https://api.github.com/users/aabc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/aabc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "emoose",
      "id": 1755499,
      "node_id": "MDQ6VXNlcjE3NTU0OTk=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1755499?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/emoose",
      "html_url": "https://github.com/emoose",
      "followers_url": "https://api.github.com/users/emoose/followers",
      "following_url": "https://api.github.com/users/emoose/following{/other_user}",
      "gists_url": "https://api.github.com/users/emoose/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/emoose/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/emoose/subscriptions",
      "organizations_url": "https://api.github.com/users/emoose/orgs",
      "repos_url": "https://api.github.com/users/emoose/repos",
      "events_url": "https://api.github.com/users/emoose/events{/privacy}",
      "received_events_url": "https://api.github.com/users/emoose/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcfy2",
      "id": 5327677,
      "node_id": "MDQ6VXNlcjUzMjc2Nzc=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/5327677?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcfy2",
      "html_url": "https://github.com/abcfy2",
      "followers_url": "https://api.github.com/users/abcfy2/followers",
      "following_url": "https://api.github.com/users/abcfy2/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcfy2/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcfy2/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcfy2/subscriptions",
      "organizations_url": "https://api.github.com/users/abcfy2/orgs",
      "repos_url": "https://api.github.com/users/abcfy2/repos",
      "events_url": "https://api.github.com/users/abcfy2/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcfy2/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "we-taper",
      "id": 6148706,
      "node_id": "MDQ6VXNlcjYxNDg3MDY=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/6148706?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/we-taper",
      "html_url": "https://github.com/we-taper",
      "followers_url": "https://api.github.com/users/we-taper/followers",
      "following_url": "https://api.github.com/users/we-taper/following{/other_user}",
      "gists_url": "https://api.github.com/users/we-taper/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/we-taper/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/we-taper/subscriptions",
      "organizations_url": "https://api.github.com/users/we-taper/orgs",
      "repos_url": "https://api.github.com/users/we-taper/repos",
      "events_url": "https://api.github.com/users/we-taper/events{/privacy}",
      "received_events_url": "https://api.github.com/users/we-taper/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Aqours",
      "id": 8586286,
      "node_id": "MDQ6VXNlcjg1ODYyODY=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/8586286?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Aqours",
      "html_url": "https://github.com/Aqours",
      "followers_url": "https://api.github.com/users/Aqours/followers",
      "following_url": "https://api.github.com/users/Aqours/following{/other_user}",
      "gists_url": "https://api.github.com/users/Aqours/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Aqours/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Aqours/subscriptions",
      "organizations_url": "https://api.github.com/users/Aqours/orgs",
      "repos_url": "https://api.github.com/users/Aqours/repos",
      "events_url": "https://api.github.com/users/Aqours/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Aqours/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abchk1234",
      "id": 5509426,
      "node_id": "MDQ6VXNlcjU1MDk0MjY=",
      "avatar_url": "https://avatars2.githubusercontent.com/u/5509426?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abchk1234",
      "html_url": "https://github.com/abchk1234",
      "followers_url": "https://api.github.com/users/abchk1234/followers",
      "following_url": "https://api.github.com/users/abchk1234/following{/other_user}",
      "gists_url": "https://api.github.com/users/abchk1234/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abchk1234/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abchk1234/subscriptions",
      "organizations_url": "https://api.github.com/users/abchk1234/orgs",
      "repos_url": "https://api.github.com/users/abchk1234/repos",
      "events_url": "https://api.github.com/users/abchk1234/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abchk1234/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcang",
      "id": 4199439,
      "node_id": "MDQ6VXNlcjQxOTk0Mzk=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/4199439?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcang",
      "html_url": "https://github.com/abcang",
      "followers_url": "https://api.github.com/users/abcang/followers",
      "following_url": "https://api.github.com/users/abcang/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcang/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcang/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcang/subscriptions",
      "organizations_url": "https://api.github.com/users/abcang/orgs",
      "repos_url": "https://api.github.com/users/abcang/repos",
      "events_url": "https://api.github.com/users/abcang/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcang/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shsjxzh",
      "id": 25194819,
      "node_id": "MDQ6VXNlcjI1MTk0ODE5",
      "avatar_url": "https://avatars1.githubusercontent.com/u/25194819?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shsjxzh",
      "html_url": "https://github.com/shsjxzh",
      "followers_url": "https://api.github.com/users/shsjxzh/followers",
      "following_url": "https://api.github.com/users/shsjxzh/following{/other_user}",
      "gists_url": "https://api.github.com/users/shsjxzh/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shsjxzh/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shsjxzh/subscriptions",
      "organizations_url": "https://api.github.com/users/shsjxzh/orgs",
      "repos_url": "https://api.github.com/users/shsjxzh/repos",
      "events_url": "https://api.github.com/users/shsjxzh/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shsjxzh/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcdw",
      "id": 1218615,
      "node_id": "MDQ6VXNlcjEyMTg2MTU=",
      "avatar_url": "https://avatars3.githubusercontent.com/u/1218615?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcdw",
      "html_url": "https://github.com/abcdw",
      "followers_url": "https://api.github.com/users/abcdw/followers",
      "following_url": "https://api.github.com/users/abcdw/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcdw/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcdw/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcdw/subscriptions",
      "organizations_url": "https://api.github.com/users/abcdw/orgs",
      "repos_url": "https://api.github.com/users/abcdw/repos",
      "events_url": "https://api.github.com/users/abcdw/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcdw/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abc873693",
      "id": 15196250,
      "node_id": "MDQ6VXNlcjE1MTk2MjUw",
      "avatar_url": "https://avatars1.githubusercontent.com/u/15196250?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abc873693",
      "html_url": "https://github.com/abc873693",
      "followers_url": "https://api.github.com/users/abc873693/followers",
      "following_url": "https://api.github.com/users/abc873693/following{/other_user}",
      "gists_url": "https://api.github.com/users/abc873693/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abc873693/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abc873693/subscriptions",
      "organizations_url": "https://api.github.com/users/abc873693/orgs",
      "repos_url": "https://api.github.com/users/abc873693/repos",
      "events_url": "https://api.github.com/users/abc873693/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abc873693/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcijkxyz",
      "id": 2009649,
      "node_id": "MDQ6VXNlcjIwMDk2NDk=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/2009649?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcijkxyz",
      "html_url": "https://github.com/abcijkxyz",
      "followers_url": "https://api.github.com/users/abcijkxyz/followers",
      "following_url": "https://api.github.com/users/abcijkxyz/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcijkxyz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcijkxyz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcijkxyz/subscriptions",
      "organizations_url": "https://api.github.com/users/abcijkxyz/orgs",
      "repos_url": "https://api.github.com/users/abcijkxyz/repos",
      "events_url": "https://api.github.com/users/abcijkxyz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcijkxyz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcoathup",
      "id": 28278242,
      "node_id": "MDQ6VXNlcjI4Mjc4MjQy",
      "avatar_url": "https://avatars0.githubusercontent.com/u/28278242?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcoathup",
      "html_url": "https://github.com/abcoathup",
      "followers_url": "https://api.github.com/users/abcoathup/followers",
      "following_url": "https://api.github.com/users/abcoathup/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcoathup/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcoathup/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcoathup/subscriptions",
      "organizations_url": "https://api.github.com/users/abcoathup/orgs",
      "repos_url": "https://api.github.com/users/abcoathup/repos",
      "events_url": "https://api.github.com/users/abcoathup/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcoathup/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "yqfang",
      "id": 4661029,
      "node_id": "MDQ6VXNlcjQ2NjEwMjk=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/4661029?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/yqfang",
      "html_url": "https://github.com/yqfang",
      "followers_url": "https://api.github.com/users/yqfang/followers",
      "following_url": "https://api.github.com/users/yqfang/following{/other_user}",
      "gists_url": "https://api.github.com/users/yqfang/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/yqfang/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/yqfang/subscriptions",
      "organizations_url": "https://api.github.com/users/yqfang/orgs",
      "repos_url": "https://api.github.com/users/yqfang/repos",
      "events_url": "https://api.github.com/users/yqfang/events{/privacy}",
      "received_events_url": "https://api.github.com/users/yqfang/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "roberthopman",
      "id": 3865531,
      "node_id": "MDQ6VXNlcjM4NjU1MzE=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3865531?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/roberthopman",
      "html_url": "https://github.com/roberthopman",
      "followers_url": "https://api.github.com/users/roberthopman/followers",
      "following_url": "https://api.github.com/users/roberthopman/following{/other_user}",
      "gists_url": "https://api.github.com/users/roberthopman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/roberthopman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/roberthopman/subscriptions",
      "organizations_url": "https://api.github.com/users/roberthopman/orgs",
      "repos_url": "https://api.github.com/users/roberthopman/repos",
      "events_url": "https://api.github.com/users/roberthopman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/roberthopman/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ABcDexter",
      "id": 7236257,
      "node_id": "MDQ6VXNlcjcyMzYyNTc=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/7236257?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ABcDexter",
      "html_url": "https://github.com/ABcDexter",
      "followers_url": "https://api.github.com/users/ABcDexter/followers",
      "following_url": "https://api.github.com/users/ABcDexter/following{/other_user}",
      "gists_url": "https://api.github.com/users/ABcDexter/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ABcDexter/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ABcDexter/subscriptions",
      "organizations_url": "https://api.github.com/users/ABcDexter/orgs",
      "repos_url": "https://api.github.com/users/ABcDexter/repos",
      "events_url": "https://api.github.com/users/ABcDexter/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ABcDexter/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "ABC10946",
      "id": 42955848,
      "node_id": "MDQ6VXNlcjQyOTU1ODQ4",
      "avatar_url": "https://avatars3.githubusercontent.com/u/42955848?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/ABC10946",
      "html_url": "https://github.com/ABC10946",
      "followers_url": "https://api.github.com/users/ABC10946/followers",
      "following_url": "https://api.github.com/users/ABC10946/following{/other_user}",
      "gists_url": "https://api.github.com/users/ABC10946/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/ABC10946/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/ABC10946/subscriptions",
      "organizations_url": "https://api.github.com/users/ABC10946/orgs",
      "repos_url": "https://api.github.com/users/ABC10946/repos",
      "events_url": "https://api.github.com/users/ABC10946/events{/privacy}",
      "received_events_url": "https://api.github.com/users/ABC10946/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcdan",
      "id": 15849319,
      "node_id": "MDQ6VXNlcjE1ODQ5MzE5",
      "avatar_url": "https://avatars3.githubusercontent.com/u/15849319?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcdan",
      "html_url": "https://github.com/abcdan",
      "followers_url": "https://api.github.com/users/abcdan/followers",
      "following_url": "https://api.github.com/users/abcdan/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcdan/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcdan/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcdan/subscriptions",
      "organizations_url": "https://api.github.com/users/abcdan/orgs",
      "repos_url": "https://api.github.com/users/abcdan/repos",
      "events_url": "https://api.github.com/users/abcdan/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcdan/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "letranloc",
      "id": 5153690,
      "node_id": "MDQ6VXNlcjUxNTM2OTA=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/5153690?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/letranloc",
      "html_url": "https://github.com/letranloc",
      "followers_url": "https://api.github.com/users/letranloc/followers",
      "following_url": "https://api.github.com/users/letranloc/following{/other_user}",
      "gists_url": "https://api.github.com/users/letranloc/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/letranloc/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/letranloc/subscriptions",
      "organizations_url": "https://api.github.com/users/letranloc/orgs",
      "repos_url": "https://api.github.com/users/letranloc/repos",
      "events_url": "https://api.github.com/users/letranloc/events{/privacy}",
      "received_events_url": "https://api.github.com/users/letranloc/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcsharp",
      "id": 773616,
      "node_id": "MDQ6VXNlcjc3MzYxNg==",
      "avatar_url": "https://avatars3.githubusercontent.com/u/773616?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcsharp",
      "html_url": "https://github.com/abcsharp",
      "followers_url": "https://api.github.com/users/abcsharp/followers",
      "following_url": "https://api.github.com/users/abcsharp/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcsharp/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcsharp/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcsharp/subscriptions",
      "organizations_url": "https://api.github.com/users/abcsharp/orgs",
      "repos_url": "https://api.github.com/users/abcsharp/repos",
      "events_url": "https://api.github.com/users/abcsharp/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcsharp/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcdxyzk",
      "id": 3094675,
      "node_id": "MDQ6VXNlcjMwOTQ2NzU=",
      "avatar_url": "https://avatars1.githubusercontent.com/u/3094675?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcdxyzk",
      "html_url": "https://github.com/abcdxyzk",
      "followers_url": "https://api.github.com/users/abcdxyzk/followers",
      "following_url": "https://api.github.com/users/abcdxyzk/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcdxyzk/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcdxyzk/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcdxyzk/subscriptions",
      "organizations_url": "https://api.github.com/users/abcdxyzk/orgs",
      "repos_url": "https://api.github.com/users/abcdxyzk/repos",
      "events_url": "https://api.github.com/users/abcdxyzk/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcdxyzk/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "abcdjdj",
      "id": 4457834,
      "node_id": "MDQ6VXNlcjQ0NTc4MzQ=",
      "avatar_url": "https://avatars0.githubusercontent.com/u/4457834?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/abcdjdj",
      "html_url": "https://github.com/abcdjdj",
      "followers_url": "https://api.github.com/users/abcdjdj/followers",
      "following_url": "https://api.github.com/users/abcdjdj/following{/other_user}",
      "gists_url": "https://api.github.com/users/abcdjdj/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/abcdjdj/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/abcdjdj/subscriptions",
      "organizations_url": "https://api.github.com/users/abcdjdj/orgs",
      "repos_url": "https://api.github.com/users/abcdjdj/repos",
      "events_url": "https://api.github.com/users/abcdjdj/events{/privacy}",
      "received_events_url": "https://api.github.com/users/abcdjdj/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
"""
}
